### ISSUE TITLE
Trouble provisioning grafana-llm-app

### ISSUE THREAD

**Issue by chewrocca** [grafana/grafana-llm-app#369]
Receiving the following message in Grafana logs:

`logger=plugin.grafana-llm-app t=2024-05-31T20:42:26.774942632Z level=warn msg="Could not get LLM Gateway URL from config, the LLM Gateway support is disabled"
logger=plugin.grafana-llm-app t=2024-05-31T20:42:26.774987423Z level=warn msg="Unable to get service account token" err="PluginAppClientSecret not set in config"`

I have the following provisioned:

```sh
  - type: 'grafana-llm-app'
    disabled: false
    jsonData:
      openAI:
        url: https://api.openai.com
    secureJsonData:
      openAIKey: ${OPENAI_API_KEY}
```

I'm trying to run this in Grafana OSS 11.0.0 with plugin version 0.10.4.

**Comment by sd2k** [comment]
Hi @chewrocca - just to check, is the LLM app actually not working with those settings? That log line is just a warning which will be logged if Grafana isn't running the `externalServiceAccounts` feature toggle, but it shouldn't be a problem for normal usage.

**Comment by chewrocca** [comment]
Correct, it's not working.  Clicking "Auto-generate" doesn't seem to work as desired.  

<img width="596" alt="image" src="https://github.com/grafana/grafana-llm-app/assets/17680862/f3caced7-3fb1-4a1b-83d4-0361027dd998">

**Comment by chewrocca** [comment]
@sd2k are there different settings I should use for provisioning besides the settings I pasted?

**Comment by sd2k** [comment]
@chewrocca could you try including something like this?:

```yaml
  - type: 'grafana-llm-app'
    disabled: false
    jsonData:
      openAI:
        provider: openai
        url: https://api.openai.com
    secureJsonData:
      openAIKey: ${OPENAI_API_KEY}
```

i.e. the `provider` key? if not we may need to look for any relevant logs, either from the Grafana backend or frontend.
