### ISSUE TITLE
Gemini Limitations

### ISSUE THREAD

**Issue by sthomson-wyn** [grafana/grafana-llm-app#628]
This isn't necessarily a request to fix this, as there are workarounds. Just wanted to document some things I ran into while trying to set this plugin up with Gemini to hopefully save somebody else some time.

Gemini has an openai compatible endpoint: https://ai.google.dev/gemini-api/docs/openai however, due to the default for a "custom" provider having the "/v1" path appended to it https://github.com/grafana/grafana-llm-app/blob/63c68d589ad6a9f82b5ed30f1c035e14e496c149/packages/grafana-llm-app/pkg/plugin/openai_provider.go#L27 it won't work without a proxy (google expects `https://generativelanguage.googleapis.com/v1beta/openai`)

Also, when choosing a proxy, it's important to consider that Gemini doesn't support `"role": "system"` messages. I tried https://github.com/zhu327/gemini-openai-proxy but that doesn't change the role automatically. https://github.com/zuisong/gemini-openai-proxy does, however.

So in the end I got it working by using https://github.com/zuisong/gemini-openai-proxy.

It would be nice if this plugin offered a way to configure the default path and the default role, but the zuisong proxy should be good enough for most people to get going with Gemini.

**Comment by azunna1** [comment]
> Would be best if there was native support for Gemini intead of having to use a proxy

Actually, you don't need to use a proxy. This is my plugin provisioning yaml

```
- type: grafana-llm-app
    jsonData:
      provider: custom
      models:
        default: base
        mapping:
          base: gemini-2.5-pro
          large: gemini-3.1-pro-preview
      openAI:
        url: https://generativelanguage.googleapis.com
        apiPath: v1beta/openai
    secureJsonData:
      openAIKey: ${GEMINI_API_KEY}
```
It should work fine
